version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: shadowsocks/android-ndk-go
    environment:
      JVM_OPTS: -Xmx3500m
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run:
          command: |
            go get -d ./...
            go get golang.org/x/mobile/cmd/gomobile
            alias gomobile=../go/bin/gomobile
            ./build_android.sh
      - store_artifacts:
          path: /build/android
